# Generated by Django 4.2.1 on 2023-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=45, null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
