# Generated by Django 4.2.1 on 2023-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educando_eco', '0002_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
