# Generated by Django 4.2.1 on 2023-06-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('educando_eco', '0005_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='grupos',
            field=models.ManyToManyField(related_name='roles', to='auth.group'),
        ),
    ]
