# Generated by Django 4.2.1 on 2023-06-05 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educando_eco', '0006_rol_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscurso',
            name='avance_curso',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
