# Generated by Django 4.2.1 on 2023-06-05 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educando_eco', '0007_miscurso_avance_curso_alter_curso_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('importe_total', models.FloatField(null=True)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra realizada',
                'verbose_name_plural': 'Compras realizadas',
                'db_table': 'compra',
            },
        ),
    ]
