# Generated by Django 4.2.1 on 2023-06-05 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educando_eco', '0008_carrito_id_usuario_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
    ]
