# Generated by Django 4.2.1 on 2023-06-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educando_eco', '0009_alter_carrito_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
